### PR TITLE
chore: upgrade vite to v5

### LINKED ISSUE #55: Support Vite 5
Add support for Vite 5.

Current configuration:

```
"peerDependencies": {
    "vite": "^2.0.0 || ^3.0.0 || ^4.0.0"
},
```

In the meantime, for a temporary workaround (in your own package.json):

```
"overrides": {
    "vite": "5.0.0"
}
```

### PR DESCRIPTION
**Pull request by maxnowack**
resolves #55

### CODE REVIEW

**Comment by TomPlum** [comment]
While updating the peer dependencies will fix the npm installation in consumers, don't we want to also bump the version of vite to v5 that the source is compiling and using? So the plugin is tested against the version its declaring its compatible with

**Comment by maxnowack** [comment]
@TomPlum you're totally right. I've updated the PR

**Comment by daiky00** [comment]
@TomPlum can you please review? I need this PR to get my stuff working

**Comment by maxnowack** [comment]
Hello @daiky00, please note that @TomPlum isn't responsible for managing this repository, so he can't merge your pull request. The only person with merge authority here is @davidmyersdev. However, repeatedly contacting him probably won't expedite the process. I'm sure he's already aware of the issue and he will look into it, when he has the time.

If you need a quick solution, consider forking the package or implementing the temporary fix suggested in issue #55. Persistently nudging others is unlikely to accelerate the resolution.

**Comment by davidmyersdev** [comment]
Hey, @maxnowack! Thanks so much for the PR. I want to make sure we're still testing other versions of Vite, so I'll likely need to modify this a bit after I merge it. That said, I'll try to get an initial release out today to fix the peer dependency and worry about supporting multiple versions after that.

**Comment by maxnowack** [comment]
@davidmyersdev thanks for merging. I already have an idea in mind how testing multiple versions of peer dependencies can be achieved. Just let me now if you want me to open a pull request for that 🙂

**Comment by davidmyersdev** [comment]
No problem at all! 😄 This was released in [`v0.17.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.17.0).

**Pull request merged**
